version: '3.8'

services:
  matchmaking_app:
    build: .
    container_name: matchmaking_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    restart: unless-stopped
